// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var array1, array2, array3, array4, board, generateTitle, masterArray, ppArray, randomIndex, randomValue, x, y, _i, _j;
    ppArray = function(array) {
      var row, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        row = array[_i];
        _results.push(console.log(row));
      }
      return _results;
    };
    this.board = [0, 1, 2, 3].map(function(x) {
      return [0, 1, 2, 3].map(function(y) {
        return 0;
      });
    });
    ppArray(this.board);
    array1 = [0, 1, 2, 3];
    array2 = [0, 1, 2, 3];
    array3 = [0, 1, 2, 3];
    array4 = [0, 1, 2, 3];
    masterArray = function() {
      var x;
      return x = array1 + array2 + array3 + array4;
    };
    masterArray();
    board = [];
    for (x = _i = 0; _i <= 3; x = ++_i) {
      board[x] = [];
      for (y = _j = 0; _j <= 3; y = ++_j) {
        board[x][y] = 0;
      }
    }
    ppArray(board);
    generateTitle = function(board) {};
    randomIndex = function(x) {
      var i, _k, _results;
      Math.floor(Math.random() * x);
      _results = [];
      for (i = _k = 0; _k <= 1000; i = ++_k) {
        _results.push(console.log(randomIndex()));
      }
      return _results;
    };
    randomValue = function() {
      var val, values;
      values = [2, 2, 2, 4];
      val = values[randomIndex(values.length) * 3];
      return console.log(randomValues);
    };
    return console.log(ppArray(this.board));
  });

}).call(this);

//# sourceMappingURL=main.map
